name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deployment
        run: curl -X POST "https://api.render.com/deploy/srv-d8b9nr5ckfvc73cqlql0?key=P8Hbrahsj6w"
